#
# Settings for SPA development, where the token handler is deployed to AWS
#
settings:
  stage: 'dev'
  domainName: 'api.authsamples-dev.com'
  certificateDomainName: 'authsamples-dev.com'
  basePath: 'tokenhandler'
