#
# Specific settings for local development
#
settings:
  # Sets event.requestContext.stage to this value
  stage: 'local'

  # These are dummy values for when running on a development computer, to keep Serverless happy
  proxyHostName: 'api-spa.mycompany.com'
  certificateDomainName: 'mycompany.com'
  trustedOrigin: 'https://web.mycompany.com'
  trustedDevOrigin: 'https://web.mycompany.com'
